[package]
name = "meilisearch-tokenizer"
version = "0.2.7"
license = "MIT"
authors = ["Many <many@meilisearch.com>"]
edition = "2021"

[dependencies]
character_converter = "1.0.0"
cow-utils = "0.1"
deunicode = "1.1.1"
fst = "0.4"
jieba-rs = "0.6"
once_cell = "1.5.2"
slice-group-by = "0.2.6"
unicode-segmentation = "1.6.0"
whatlang = "0.13.0"
lindera = "0.10.0"
lindera-core = "0.10.0"
maplit = "1.0.2"

[dev-dependencies]
criterion = "0.3"
jemallocator = "0.3.0"

[[bench]]
name = "bench"
harness = false

