[package]
name = "meilisearch-tokenizer"
version = "0.1.0"
license = "MIT"
authors = ["Many <many@meilisearch.com>"]
edition = "2018"

[dependencies]
character_converter = "1.0.0"
cow-utils = "0.1"
deunicode = "1.1.1"
jieba-rs = "0.6"
once_cell = "1.5.2"
slice-group-by = "0.2.6"
unicode-segmentation = "1.6.0"
whatlang = "0.9.0"
fst = "0.4"
