[package]
name = "charabia"
version = "0.7.1"
license = "MIT"
authors = ["Many <many@meilisearch.com>"]
edition = "2021"
description = "A simple library to detect the language, tokenize the text and normalize the tokens"
documentation = "https://docs.rs/charabia"
repository = "https://github.com/meilisearch/charabia"
keywords = ["segmenter", "tokenizer", "normalize", "language"]
categories = ["text-processing"]
exclude = ["dictionaries/txt/thai/words.txt"]

[dependencies]
cow-utils = "0.1"
csv = "1.1"
deunicode = "1.1.1"
finl_unicode = { version= "1.2.0", optional = true }
fst = "0.4"
jieba-rs = { version = "0.6", optional = true }
once_cell = "1.5.2"
serde = "1.0"
slice-group-by = "0.3.0"
unicode-segmentation = "1.6.0"
whatlang = "0.16.1"
lindera = { version = "=0.23.0", default-features = false, optional = true }
pinyin = { version = "0.9", default-features = false, features = [
  "with_tone",
], optional = true }
wana_kana = { version = "2.1.0", optional = true }
unicode-normalization = "0.1.22"
irg-kvariants = "0.1.0"
litemap = "0.6.1"
zerovec = "0.9.3"
icu = { version = "1.3.0", features = ["serde"] , optional = true }
icu_provider_blob = { version = "1.3.0", optional = true }
icu_provider = { version = "1.3.0", features = ["sync"], optional = true }

[features]
default = ["chinese", "hebrew", "japanese", "thai", "korean", "greek", "latin-camelcase", "khmer"]

# allow chinese specialized tokenization
chinese = ["dep:pinyin", "dep:jieba-rs"]

# allow hebrew specialized tokenization
hebrew = []

# allow japanese specialized tokenization
japanese = ["lindera/ipadic", "lindera/ipadic-compress"]
japanese-transliteration = ["dep:wana_kana"]

# allow korean specialized tokenization
korean = ["lindera/ko-dic", "lindera/ko-dic-compress"]

# allow thai specialized tokenization
thai = []

# allow greek specialized tokenization
greek = []

# allow splitting camelCase latin words
latin-camelcase = ["dep:finl_unicode"]

khmer = ["dep:icu", "dep:icu_provider_blob", "dep:icu_provider"]

[dev-dependencies]
criterion = "0.3"
jemallocator = "0.3.0"

[[bench]]
name = "bench"
harness = false
