contact_links:
  - name: Feature request & feedback
    url: https://github.com/meilisearch/product/discussions/categories/feedback-feature-proposal
    about: The feature requests and feedback regarding the already existing features are not managed in this repository. Please open a discussion in our dedicated product repository.
